---
- name: Install termite configuration file
  copy:
    src: config
    dest: {{ ansible_user_dir }}/.config/termite/config

- name: Install gtk configuration file (padding in terminal)
  copy:
    src: gtk.css
    dest: {{ ansible_user_dir }}/.config/gtk-3.0/gtk.css
