---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - g++
    - libgtk-3-dev
    - gtk-doc-tools
    - gnutls-bin
    - valac
    - intltool
    - libpcre2-dev
    - libglib3.0-cil-dev
    - libgnutls28-dev
    - libgirepository1.0-dev
    - libxml2-utils
    - gperf
  become: yes
  become_user: root

- name: Clone vte-ng repository
  git:
    repo: 'https://github.com/thestinger/vte-ng.git'
    dest: /tmp/vte-ng

- name: Run autogen.sh in vte-ng
  command: ./autogen.sh
  args:
    chdir: /tmp/vte-ng
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH

- name: Make vte-ng
  make:
    chdir: /tmp/vte-ng
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH

- name: Make install vte-ng
  make:
    chdir: /tmp/vte-ng
    target: install
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH
  become: yes
  become_user: root

- name: Clone termite repository
  git:
    repo: 'https://github.com/thestinger/termite.git'
    dest: /tmp/termite
    recursive: yes
    force: yes

- name: Make termite
  make:
    chdir: /tmp/termite
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH

- name: Make install termite
  make:
    chdir: /tmp/termite
    target: install
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH
  become: yes
  become_user: root

- name: Run ldconfig
  command: ldconfig
  args:
    chdir: /tmp/termite
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH
  become: yes
  become_user: root

- name: Create terminfo directory structure
  file:
    path: /lib/terminfo/x
    state: directory
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH
  become: yes
  become_user: root

- name: Symlink xterm-termite
  file:
    path: /lib/terminfo/x/xterm-termite
    src: /usr/local/share/terminfo/x/xterm-termite
    state: link
  environment:
    LIBRARY_PATH: /usr/include/gtk-3.0:$LIBRARY_PATH
  become: yes
  become_user: root
