let PLUGIN_PATH = expand('~/.vim/autoload/plug.vim')

if has('vim_starting') && empty(glob(PLUGIN_PATH))
    silent execute '!curl -fLo ' . PLUGIN_PATH . ' --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Inform Plug that we start our plugin installation
call plug#begin('~/.vim/plugged')

" Git plugins
Plug 'jreybert/vimagit'

" colorschemes
Plug 'altercation/vim-colors-solarized'

" Utility
Plug 'terryma/vim-multiple-cursors'
Plug 'rstacruz/vim-closer'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-eunuch'

" Ansible
Plug 'pearofducks/ansible-vim', { 'do': 'cd ./UltiSnips; python2 generate.py' }

" Markdown
Plug 'junegunn/goyo.vim', { 'for': 'markdown' }
Plug 'tpope/vim-markdown', { 'for': 'markdown' }

" Vim only
if !has('nvim')
  Plug 'airblade/vim-gitgutter'
endif

" Neovim only
" Vim only
if has('nvim')
  Plug 'roxma/nvim-completion-manager'
endif

" Add plugins to &runtimepath
call plug#end()

filetype plugin indent on

syntax on
set background=dark
"colorscheme industry

set laststatus=2
set number

set tabstop=2
set softtabstop=0 noexpandtab
set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab

" Disable visual bell in Terminal
set visualbell t_vb=
set noeb vb t_vb=

" Sets italic, if supported
set t_ZH=[3m
set t_ZR=[23m

" Keeps at least 3 lines above the cursor
set scrolloff=3

"" Set modelines off due to possible security flaws
set modelines=0
set nomodeline

" Sets vim to use a ruler which shows the
" " line, column number.
set ruler
set number
set relativenumber

" Sets the title to the filename
set title
set titleold="Terminal"
set titlestring=vim\ \-\ %F

set statusline=%F%m%r%h%w%=%y\ [%l:%c\/%L]

source $HOME/.vim/keys.vim

