---
- name: Install neovim
  apt:
    name: neovim
    state: latest
  become: yes
  become_user: root

- name: Create neovim config directory
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    owner: "{{ ansible_user_id }}"
    state: directory

- name: Install neovim config
  copy:
    src: init.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    owner: "{{ ansible_user_id }}"

- name: Create plug directory
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/autoload"
    state: directory
    owner: "{{ ansible_user_id}}"

- name: Install plug for nvim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/autoload/plug.vim"
