---
- name: Create nerdfonts fonts directory
  file:
    path: /usr/local/share/fonts/NerdFonts
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0777
  become: yes
  become_user: root

- name: Download Sauce Code Pro Complete Nerd font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf
    dest: /usr/local/share/fonts/NerdFonts/Sauce Code Pro Nerd Font Complete.ttf 
  notify: rebuild font cache
